name: ARTIFACT USE

on: push

env: 
  ARTIFACT_NAME: 'bumchik'

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
